# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# DEVISE Varibles required for creating the initial administrative user
#
# ADMIN_FIRST_NAME
# ADMIN_LAST_NAME
# ADMIN_PHONE
# ADMIN_EMAIL
# ADMIN_PASSWORD

# SMTP Server Variables
#
# SMTP_HOST
# SMTP_PORT
# SMTP_DOMAIN
# SMTP_USER
# SMTP_PASSWORD


# NOTE: You can setup variables by environment see Figaro documentation
# for details - https://github.com/laserlemon/figaro

development:
  SMTP_HOST: <%= ENV['SMTP_HOST'] %>
  SMTP_PORT: <%= ENV['SMTP_PORT'] %>
  SMTP_DOMAIN: <%= ENV['SMTP_DOMAIN'] %>
  SMTP_USER: <%= ENV['SMTP_USER'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  
  ADMIN_FIRST_NAME: <%= ENV['ADMIN_FIRST_NAME'] %>
  ADMIN_LAST_NAME: <%= ENV['ADMIN_LAST_NAME'] %>
  ADMIN_PHONE: <%= ENV['ADMIN_PHONE'] %>
  ADMIN_EMAIL: <%= ENV['ADMIN_EMAIL'] %>
  ADMIN_PASSWORD: <%= ENV['ADMIN_PASSWORD'] %> 
  
production:
  SMTP_HOST: <%= ENV['SMTP_HOST'] %>
  SMTP_PORT: <%= ENV['SMTP_PORT'] %>
  SMTP_DOMAIN: <%= ENV['SMTP_DOMAIN'] %>
  SMTP_USER: <%= ENV['SMTP_USER'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  
  ADMIN_FIRST_NAME: <%= ENV['ADMIN_FIRST_NAME'] %>
  ADMIN_LAST_NAME: <%= ENV['ADMIN_LAST_NAME'] %>
  ADMIN_PHONE: <%= ENV['ADMIN_PHONE'] %>
  ADMIN_EMAIL: <%= ENV['ADMIN_EMAIL'] %>
  ADMIN_PASSWORD: <%= ENV['ADMIN_PASSWORD'] %>  
